<a href="https://colab.research.google.com/github/RohanCoderiiitb/FFT-Processor/blob/main/FFT_Processor_Evaluation_Assistant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Comparission between FFT results for data in FP4 and FP8 format

We are comparing results obtained by using FP4(E2M1), FP4(E1M2), FP8 with those of FP32.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import numpy as np

def quantize_hw(x, exp_bits, mant_bits, bias):
    if x == 0: return 0.0

    sign = np.sign(x)
    val = abs(x)

    exp = int(np.floor(np.log2(val))) + bias

    if exp <= 0:
        return 0.0

    max_exp = (2**exp_bits) - 1
    if exp >= max_exp:
        max_val = (1 + (2**mant_bits - 1) / 2**mant_bits) * (2**(max_exp - bias))
        return sign * max_val

    mantissa_val = (val / (2**(exp - bias))) - 1.0
    steps = 2**mant_bits
    mant_q = np.round(mantissa_val * steps) / steps

    if mant_q >= 1.0:
        mant_q = 0.0
        exp += 1
        if exp >= max_exp:
            return sign * ((1 + (steps-1)/steps) * (2**(max_exp - bias)))

    return sign * (1.0 + mant_q) * (2**(exp - bias))

def quant_e2m1(x): return quantize_hw(x, exp_bits=2, mant_bits=1, bias=1)
def quant_e1m2(x): return quantize_hw(x, exp_bits=1, mant_bits=2, bias=0)
def quant_fp8(x):  return quantize_hw(x, exp_bits=4, mant_bits=3, bias=7)

In [ ]:
def hardware_butterfly(A, B, W, q_params):
    eb, mb, bias = q_params

    ac = quantize_hw(B.real * W.real, eb, mb, bias)
    bd = quantize_hw(B.imag * W.imag, eb, mb, bias)
    ad = quantize_hw(B.real * W.imag, eb, mb, bias)
    bc = quantize_hw(B.imag * W.real, eb, mb, bias)

    wb_re = quantize_hw(ac - bd, eb, mb, bias)
    wb_im = quantize_hw(ad + bc, eb, mb, bias)
    WB = complex(wb_re, wb_im)

    x_re = quantize_hw(A.real + WB.real, eb, mb, bias)
    x_im = quantize_hw(A.imag + WB.imag, eb, mb, bias)
    y_re = quantize_hw(A.real - WB.real, eb, mb, bias)
    y_im = quantize_hw(A.imag - WB.imag, eb, mb, bias)

    return complex(x_re, x_im), complex(y_re, y_im)

In [ ]:
E2M1_ROM = {
    0:  complex(1.0,  0.0),  1:  complex(1.0,  0.0),   2:  complex(1.0, -0.5),
    3:  complex(1.0, -0.5),  4:  complex(0.5, -0.5),  5:  complex(0.5, -1.0),
    6:  complex(0.5, -1.0),  7:  complex(0.0, -1.0),  8:  complex(0.0, -1.0),
    9:  complex(0.0,  1.0),  10: complex(0.5,  1.0),  11: complex(0.5,  1.0),
    12: complex(0.5,  0.5),  13: complex(1.0,  0.5),  14: complex(1.0,  0.5),
    15: complex(1.0,  0.0)
}

def generate_rom(exp_bits, mant_bits, bias, points=16):
    rom = {}
    for k in range(points):
        angle = -2j * np.pi * k / 32
        w_ideal = np.exp(angle)
        re = quantize_hw(w_ideal.real, exp_bits, mant_bits, bias)
        im = quantize_hw(w_ideal.imag, exp_bits, mant_bits, bias)
        rom[k] = complex(re, im)
    return rom

E1M2_ROM = generate_rom(1, 2, 0)
FP8_ROM  = generate_rom(4, 3, 7)

In [ ]:
def get_hardware_twiddle(k, n, arch_tuple):
    eb, mb, bias = arch_tuple

    scaled_k = int(k * (32 // n))

    use_conjugate = False
    if scaled_k >= 16:
        use_conjugate = True
        table_idx = 31 - scaled_k
    else:
        table_idx = scaled_k

    if arch_tuple == (2, 1, 1):
        val = E2M1_ROM.get(table_idx, complex(0,0))
    elif arch_tuple == (1, 2, 0):
        val = E1M2_ROM.get(table_idx, complex(0,0))
    else:
        val = FP8_ROM.get(table_idx, complex(0,0))

    if use_conjugate:
        return complex(val.real, -val.imag)
    return val

In [ ]:
def run_architecture_test(x_input, arch_tuple):
    N = len(x_input)
    stages = int(np.log2(N))

    indices = [int('{:0{width}b}'.format(i, width=stages)[::-1], 2) for i in range(N)]
    x = np.array([x_input[i] for i in indices], dtype=complex)

    for stage in range(stages):
        stride = 2**stage
        for g in range(0, N, stride * 2):
            for b in range(stride):
                W_q = get_hardware_twiddle(b, stride * 2, arch_tuple)

                idx_a, idx_b = g + b, g + b + stride
                x[idx_a], x[idx_b] = hardware_butterfly(x[idx_a], x[idx_b], W_q, arch_tuple)

    return x

E2M1 = (2, 1, 1)
E1M2 = (1, 2, 0)
FP8  = (4, 3, 7)

## Testing using the following signals:
1. Single tone sinusoid
2. Dual tone sinusoid
3. Strong + Weak Signal
4. White Gaussian Noise
5. Impulse

Signal to Quantization Noise Ratio(SQNR), Shape Error and Spectral Correlation Coefficient are the metrics used to analyse the performance of different floating point architectures

## Metrics

In [ ]:
def compute_sqnr(ref, quant):
  signal_power = np.sum(np.abs(ref)**2)
  noise_power = np.sum(np.abs(ref - quant)**2)
  return 10*np.log10(signal_power/(noise_power + 1e-18))

def compute_root_mean_square_error(ref, quant):
  error = ref - quant
  mse = np.mean(np.abs(error)**2)
  return np.sqrt(mse)

def compute_mean_shape_error(ref, quant):
  mag_ref = np.abs(ref)
  mag_quant = np.abs(quant)
  p_ref = np.max(mag_ref)
  p_quant = np.max(mag_quant)
  if p_quant < 1e-12:
    shape_err = 1.0
  else:
    shape_err = np.mean(np.abs((mag_ref/p_ref) - (mag_quant/p_quant)))
  return shape_err

def compute_spectral_correlation_coefficient(ref, quant):
  mag_ref = np.abs(ref)
  mag_quant = np.abs(quant)
  p_ref = np.max(mag_ref)
  p_quant = np.max(mag_quant)
  if p_quant < 1e-12 or np.std(mag_quant)==0:
    corr = 0.0
  else:
    corr = np.corrcoef(mag_ref, mag_quant)[0,1]
  return corr

### Single Tone Sinusoid

In [ ]:
N = 32
k = 3
n = np.arange(N)
x = np.sin(2*np.pi*k*n/N)

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_architecture_test(x,E2M1)
X_fp4_e1m2 = run_architecture_test(x,E1M2)
X_fp8_e4m3 = run_architecture_test(x,FP8)

In [ ]:
import pandas as pd

data = [
    {"Signal Name": "Single Tone Sinusoid", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Single Tone Sinusoid", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Single Tone Sinusoid", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,Single Tone Sinusoid,FP4 (E2M1),3.741657,0.579919,0.437500,0.258199
1,Single Tone Sinusoid,FP4 (E1M2),4.000000,0.000000,1.000000,0.000000
2,Single Tone Sinusoid,FP8 (E4M3),0.197811,26.116184,0.007472,0.999490

### Dual Tone Sinusoid

In [ ]:
x = (np.sin(2*np.pi*3*n/N) + 0.5*np.sin(2*np.pi*5*n/N))
x = (x / np.max(np.abs(x))) * 2.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_architecture_test(x, E2M1)
X_fp4_e1m2 = run_architecture_test(x, E1M2)
X_fp8_e4m3 = run_architecture_test(x, FP8)

In [ ]:
import pandas as pd

data = [
    {"Signal Name": "Dual Tone Sinusoid", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Dual Tone Sinusoid", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Dual Tone Sinusoid", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,Dual Tone Sinusoid,FP4 (E2M1),8.173916,-2.051835,0.326068,0.286496
1,Dual Tone Sinusoid,FP4 (E1M2),6.454140,0.000000,1.000000,0.000000
2,Dual Tone Sinusoid,FP8 (E4M3),0.497344,22.263638,0.013257,0.997842

### Strong + Weak Signal

In [ ]:
x = (1.0 * np.sin(2*np.pi*3*n/N) + 0.1 * np.sin(2*np.pi*12*n/N))
x = (x / np.max(np.abs(x))) * 2.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_architecture_test(x, E2M1)
X_fp4_e1m2 = run_architecture_test(x, E1M2)
X_fp8_e4m3 = run_architecture_test(x, FP8)

In [ ]:
import pandas as pd

data = [
    {"Signal Name": "Strong + Weak Signal", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Strong + Weak Signal", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Strong + Weak Signal", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,Strong + Weak Signal,FP4 (E2M1),8.460741,-0.879306,0.367178,0.292790
1,Strong + Weak Signal,FP4 (E1M2),7.646154,0.000000,1.000000,0.000000
2,Strong + Weak Signal,FP8 (E4M3),0.743058,20.248410,0.010479,0.999363

### White Gaussian Noise

In [ ]:
np.random.seed(42)
x = np.random.normal(0, 0.5, N)
x = (x / np.max(np.abs(x))) * 2.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_architecture_test(x, E2M1)
X_fp4_e1m2 = run_architecture_test(x, E1M2)
X_fp8_e4m3 = run_architecture_test(x, FP8)

In [ ]:
import pandas as pd

data = [
    {"Signal Name": "White Gaussian Noise", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "White Gaussian Noise", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "White Gaussian Noise", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,White Gaussian Noise,FP4 (E2M1),7.621733,-2.731236,0.324403,0.301471
1,White Gaussian Noise,FP4 (E1M2),5.565343,0.000000,1.000000,0.000000
2,White Gaussian Noise,FP8 (E4M3),0.437273,22.094782,0.034712,0.987651

### Impulse Signal

In [ ]:
x = np.zeros(N)
x[0] = 1.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_architecture_test(x, E2M1)
X_fp4_e1m2 = run_architecture_test(x, E1M2)
X_fp8_e4m3 = run_architecture_test(x, FP8)

In [ ]:
import pandas as pd

data = [
    {"Signal Name": "Impulse", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Impulse", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Impulse", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

  Signal Name Data Format  RMSE  SQNR (dB)  Shape Error  Correlation
0     Impulse  FP4 (E2M1)   0.0   195.0515          0.0          0.0
1     Impulse  FP4 (E1M2)   1.0     0.0000          1.0          0.0
2     Impulse  FP8 (E4M3)   0.0   195.0515          0.0          0.0

In [ ]:
N = 32
k = 3
n = np.arange(N)
x = np.sin(2*np.pi*k*n/N)

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_architecture_test(x,E2M1)
X_fp4_e1m2 = run_architecture_test(x,E1M2)
X_fp8_e4m3 = run_architecture_test(x,FP8)

In [ ]:
import pandas as pd

data = [
    {"Signal Name": "Single Tone Sinusoid", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Single Tone Sinusoid", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Single Tone Sinusoid", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,Single Tone Sinusoid,FP4 (E2M1),3.741657,0.579919,0.437500,0.258199
1,Single Tone Sinusoid,FP4 (E1M2),4.000000,0.000000,1.000000,0.000000
2,Single Tone Sinusoid,FP8 (E4M3),0.197811,26.116184,0.007472,0.999490

### Dual Tone Sinusoid

In [ ]:
x = (np.sin(2*np.pi*3*n/N) + 0.5*np.sin(2*np.pi*5*n/N))
x = (x / np.max(np.abs(x))) * 2.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_architecture_test(x, E2M1)
X_fp4_e1m2 = run_architecture_test(x, E1M2)
X_fp8_e4m3 = run_architecture_test(x, FP8)

In [ ]:
import pandas as pd

data = [
    {"Signal Name": "Dual Tone Sinusoid", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Dual Tone Sinusoid", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Dual Tone Sinusoid", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,Dual Tone Sinusoid,FP4 (E2M1),8.173916,-2.051835,0.326068,0.286496
1,Dual Tone Sinusoid,FP4 (E1M2),6.454140,0.000000,1.000000,0.000000
2,Dual Tone Sinusoid,FP8 (E4M3),0.497344,22.263638,0.013257,0.997842

### Strong + Weak Signal

In [ ]:
x = (1.0 * np.sin(2*np.pi*3*n/N) + 0.1 * np.sin(2*np.pi*12*n/N))
x = (x / np.max(np.abs(x))) * 2.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_architecture_test(x, E2M1)
X_fp4_e1m2 = run_architecture_test(x, E1M2)
X_fp8_e4m3 = run_architecture_test(x, FP8)

In [ ]:
import pandas as pd

data = [
    {"Signal Name": "Strong + Weak Signal", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Strong + Weak Signal", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Strong + Weak Signal", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,Strong + Weak Signal,FP4 (E2M1),8.460741,-0.879306,0.367178,0.292790
1,Strong + Weak Signal,FP4 (E1M2),7.646154,0.000000,1.000000,0.000000
2,Strong + Weak Signal,FP8 (E4M3),0.743058,20.248410,0.010479,0.999363

### White Gaussian Noise

In [ ]:
np.random.seed(42)
x = np.random.normal(0, 0.5, N)
x = (x / np.max(np.abs(x))) * 2.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_architecture_test(x, E2M1)
X_fp4_e1m2 = run_architecture_test(x, E1M2)
X_fp8_e4m3 = run_architecture_test(x, FP8)

In [ ]:
import pandas as pd

data = [
    {"Signal Name": "White Gaussian Noise", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "White Gaussian Noise", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "White Gaussian Noise", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,White Gaussian Noise,FP4 (E2M1),7.621733,-2.731236,0.324403,0.301471
1,White Gaussian Noise,FP4 (E1M2),5.565343,0.000000,1.000000,0.000000
2,White Gaussian Noise,FP8 (E4M3),0.437273,22.094782,0.034712,0.987651

### Impulse Signal

In [ ]:
x = np.zeros(N)
x[0] = 1.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_architecture_test(x, E2M1)
X_fp4_e1m2 = run_architecture_test(x, E1M2)
X_fp8_e4m3 = run_architecture_test(x, FP8)

In [ ]:
import pandas as pd

data = [
    {"Signal Name": "Impulse", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Impulse", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Impulse", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

  Signal Name Data Format  RMSE  SQNR (dB)  Shape Error  Correlation
0     Impulse  FP4 (E2M1)   0.0   195.0515          0.0          0.0
1     Impulse  FP4 (E1M2)   1.0     0.0000          1.0          0.0
2     Impulse  FP8 (E4M3)   0.0   195.0515          0.0          0.0

## Implementing Radix 4 DIT FFT on data represented in FP4 E2M1

In [66]:
SCALE_FACTOR = 0.5
def scale_complex(z, q):
  return complex(
      quantize_hw(SCALE_FACTOR * z.real, *q),
      quantize_hw(SCALE_FACTOR * z.imag, *q)
  )

def hardware_butterfly_radix4(a0, a1, a2, a3, W1, W2, W3, q_params):
    b1 = hardware_complex_mul(a1, W1, q_params)
    b2 = hardware_complex_mul(a2, W2, q_params)
    b3 = hardware_complex_mul(a3, W3, q_params)

    t0_re = quantize_hw(a0.real + b2.real, *q_params)
    t0_im = quantize_hw(a0.imag + b2.imag, *q_params)
    t1_re = quantize_hw(a0.real - b2.real, *q_params)
    t1_im = quantize_hw(a0.imag - b2.imag, *q_params)

    t2_re = quantize_hw(b1.real + b3.real, *q_params)
    t2_im = quantize_hw(b1.imag + b3.imag, *q_params)

    t3_re = quantize_hw(b1.imag - b3.imag, *q_params)
    t3_im = quantize_hw(b3.real - b1.real, *q_params)

    x0 = complex(quantize_hw(t0_re + t2_re, *q_params), quantize_hw(t0_im + t2_im, *q_params))
    x2 = complex(quantize_hw(t0_re - t2_re, *q_params), quantize_hw(t0_im - t2_im, *q_params))
    x1 = complex(quantize_hw(t1_re + t3_re, *q_params), quantize_hw(t1_im + t3_im, *q_params))
    x3 = complex(quantize_hw(t1_re - t3_re, *q_params), quantize_hw(t1_im - t3_im, *q_params))

    x0 = scale_complex(x0, q_params)
    x1 = scale_complex(x1, q_params)
    x2 = scale_complex(x2, q_params)
    x3 = scale_complex(x3, q_params)

    return x0, x1, x2, x3

def hardware_complex_mul(A, W, q_params):
    eb, mb, bias = q_params
    ac = quantize_hw(A.real * W.real, eb, mb, bias)
    bd = quantize_hw(A.imag * W.imag, eb, mb, bias)
    ad = quantize_hw(A.real * W.imag, eb, mb, bias)
    bc = quantize_hw(A.imag * W.real, eb, mb, bias)

    return complex(quantize_hw(ac - bd, eb, mb, bias),
                   quantize_hw(ad + bc, eb, mb, bias))

In [67]:
def digit_reverse_4(n, stages):
    indices = []
    for i in range(n):
        res = 0
        tmp_i = i
        for _ in range(stages):
            res = (res << 2) | (tmp_i & 3)
            tmp_i >>= 2
        indices.append(res)
    return indices

In [68]:
def get_hardware_twiddle_radix4(k, n, arch_tuple):
    eb, mb, bias = arch_tuple

    scaled_k = (k * 32) // n
    scaled_k = scaled_k % 32

    use_conjugate = False
    if scaled_k >= 16:
        use_conjugate = True
        table_idx = 31 - scaled_k
    else:
        table_idx = scaled_k

    if arch_tuple == (2, 1, 1):
        val = E2M1_ROM.get(table_idx, complex(0,0))
    elif arch_tuple == (1, 2, 0):
        val = E1M2_ROM.get(table_idx, complex(0,0))
    else:
        val = FP8_ROM.get(table_idx, complex(0,0))

    if use_conjugate:
        return complex(val.real, -val.imag)
    return val

In [69]:
def run_radix4_test(x_input, arch_tuple):
    N = len(x_input)

    stages = int(np.log(N) / np.log(4))

    indices = digit_reverse_4(N, stages)
    x = np.array([x_input[i] for i in indices], dtype=complex)

    for s in range(stages):
        m = 4 ** (s + 1)
        stride = 4 ** s

        for group in range(0, N, m):
            for k in range(stride):

                W1 = get_hardware_twiddle_radix4(k, m, arch_tuple)
                W2 = get_hardware_twiddle_radix4(2*k, m, arch_tuple)
                W3 = get_hardware_twiddle_radix4(3*k, m, arch_tuple)

                idx0 = group + k
                idx1 = idx0 + stride
                idx2 = idx0 + 2 * stride
                idx3 = idx0 + 3 * stride

                results = hardware_butterfly_radix4(
                    x[idx0], x[idx1], x[idx2], x[idx3],
                    W1, W2, W3, arch_tuple
                )

                x[idx0], x[idx1], x[idx2], x[idx3] = results

    return x

In [70]:
def run_radix4_with_padding(x_input, arch_tuple):
    N = len(x_input)

    if not (N > 0 and (N & (N - 1)) == 0 and (int(np.log2(N)) % 2 == 0)):
        new_N = 4**int(np.ceil(np.log(N)/np.log(4)))

        padding = np.zeros(new_N - N, dtype=complex)
        x_input = np.concatenate([x_input, padding])
        print(f"Padded signal from {N} to {new_N} for Radix-4 compatibility.")

    return run_radix4_test(x_input, arch_tuple)

In [71]:
def align_signals(ref, quant):
    if len(ref) < len(quant):
        padding = np.zeros(len(quant) - len(ref), dtype=ref.dtype)
        ref = np.concatenate([ref, padding])
    elif len(quant) < len(ref):
        padding = np.zeros(len(ref) - len(quant), dtype=quant.dtype)
        quant = np.concatenate([quant, padding])
    return ref, quant

In [72]:
def compute_sqnr_for_radix4(ref, quant):
  ref, quant = align_signals(ref, quant)
  signal_power = np.sum(np.abs(ref)**2)
  noise_power = np.sum(np.abs(ref - quant)**2)
  return 10*np.log10(signal_power/(noise_power + 1e-18))

def compute_root_mean_square_error_for_radix4(ref, quant):
  ref, quant = align_signals(ref, quant)
  error = ref - quant
  mse = np.mean(np.abs(error)**2)
  return np.sqrt(mse)

def compute_mean_shape_error_for_radix4(ref, quant):
  ref, quant = align_signals(ref, quant)
  mag_ref = np.abs(ref)
  mag_quant = np.abs(quant)
  p_ref = np.max(mag_ref)
  p_quant = np.max(mag_quant)
  if p_quant < 1e-12:
    shape_err = 1.0
  else:
    shape_err = np.mean(np.abs((mag_ref/p_ref) - (mag_quant/p_quant)))
  return shape_err

def compute_spectral_correlation_coefficient_for_radix4(ref, quant):
  ref, quant = align_signals(ref, quant)
  mag_ref = np.abs(ref)
  mag_quant = np.abs(quant)
  p_ref = np.max(mag_ref)
  p_quant = np.max(mag_quant)
  if p_quant < 1e-12 or np.std(mag_quant)==0:
    corr = 0.0
  else:
    corr = np.corrcoef(mag_ref, mag_quant)[0,1]
  return corr

In [73]:
N = 16
k = 3
n = np.arange(N)
x = np.sin(2*np.pi*k*n/N)

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_radix4_with_padding(x,E2M1)
X_fp4_e1m2 = run_radix4_with_padding(x,E1M2)
X_fp8_e4m3 = run_radix4_with_padding(x,FP8)

In [74]:
import pandas as pd

data = [
    {"Signal Name": "Single Tone Sinusoid", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Single Tone Sinusoid", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Single Tone Sinusoid", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,Single Tone Sinusoid,FP4 (E2M1),2.828427,0.000000,1.000000,0.000000
1,Single Tone Sinusoid,FP4 (E1M2),2.828427,0.000000,1.000000,0.000000
2,Single Tone Sinusoid,FP8 (E4M3),2.121896,2.496419,0.010799,0.998407

### Dual Tone Sinusoid

In [75]:
x = (np.sin(2*np.pi*3*n/N) + 0.5*np.sin(2*np.pi*5*n/N))
x = (x / np.max(np.abs(x))) * 2.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_radix4_with_padding(x, E2M1)
X_fp4_e1m2 = run_radix4_with_padding(x, E1M2)
X_fp8_e4m3 = run_radix4_with_padding(x, FP8)

In [76]:
import pandas as pd

data = [
    {"Signal Name": "Dual Tone Sinusoid", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Dual Tone Sinusoid", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Dual Tone Sinusoid", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,Dual Tone Sinusoid,FP4 (E2M1),4.140786,0.844812,0.25000,0.487377
1,Dual Tone Sinusoid,FP4 (E1M2),4.563766,0.000000,1.00000,0.000000
2,Dual Tone Sinusoid,FP8 (E4M3),3.439889,2.455580,0.02166,0.994494

### Strong + Weak Signal

In [77]:
x = (1.0 * np.sin(2*np.pi*3*n/N) + 0.1 * np.sin(2*np.pi*12*n/N))
x = (x / np.max(np.abs(x))) * 2.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_radix4_with_padding(x, E2M1)
X_fp4_e1m2 = run_radix4_with_padding(x, E1M2)
X_fp8_e4m3 = run_radix4_with_padding(x, FP8)

In [78]:
import pandas as pd

data = [
    {"Signal Name": "Strong + Weak Signal", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Strong + Weak Signal", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Strong + Weak Signal", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,Strong + Weak Signal,FP4 (E2M1),5.027354,0.862947,0.290451,0.357226
1,Strong + Weak Signal,FP4 (E1M2),5.552478,0.000000,1.000000,0.000000
2,Strong + Weak Signal,FP8 (E4M3),4.178201,2.469951,0.019000,0.996468

### White Gaussian Noise

In [79]:
np.random.seed(42)
x = np.random.normal(0, 0.5, N)
x = (x / np.max(np.abs(x))) * 2.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_radix4_with_padding(x, E2M1)
X_fp4_e1m2 = run_radix4_with_padding(x, E1M2)
X_fp8_e4m3 = run_radix4_with_padding(x, FP8)

In [80]:
import pandas as pd

data = [
    {"Signal Name": "White Gaussian Noise", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "White Gaussian Noise", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "White Gaussian Noise", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

,Signal Name,Data Format,RMSE,SQNR (dB),Shape Error,Correlation
0,White Gaussian Noise,FP4 (E2M1),3.878423,0.120904,0.415572,0.308182
1,White Gaussian Noise,FP4 (E1M2),3.932787,0.000000,1.000000,0.000000
2,White Gaussian Noise,FP8 (E4M3),2.922233,2.579712,0.021615,0.997425

### Impulse Signal

In [81]:
x = np.zeros(N)
x[0] = 1.0

X_fft_ref = np.fft.fft(x)

X_fp4_e2m1 = run_radix4_with_padding(x, E2M1)
X_fp4_e1m2 = run_radix4_with_padding(x, E1M2)
X_fp8_e4m3 = run_radix4_with_padding(x, FP8)

In [82]:
import pandas as pd

data = [
    {"Signal Name": "Impulse", "Data Format": "FP4 (E2M1)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp4_e2m1),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp4_e2m1),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp4_e2m1),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp4_e2m1)},

    {"Signal Name": "Impulse", "Data Format": "FP4 (E1M2)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp4_e1m2),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp4_e1m2),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp4_e1m2),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp4_e1m2)},

    {"Signal Name": "Impulse", "Data Format": "FP8 (E4M3)",
     "RMSE": compute_root_mean_square_error_for_radix4(X_fft_ref, X_fp8_e4m3),
     "SQNR (dB)": compute_sqnr_for_radix4(X_fft_ref, X_fp8_e4m3),
     "Shape Error": compute_mean_shape_error_for_radix4(X_fft_ref, X_fp8_e4m3),
     "Correlation": compute_spectral_correlation_coefficient_for_radix4(X_fft_ref, X_fp8_e4m3)},
]

results_table = pd.DataFrame(data)

results_table = results_table[["Signal Name", "Data Format", "RMSE", "SQNR (dB)", "Shape Error", "Correlation"]]

print("FFT Architecture Performance Comparison Table")
print("="*80)
display(results_table)

FFT Architecture Performance Comparison Table
================================================================================

  Signal Name Data Format  RMSE  SQNR (dB)  Shape Error  Correlation
0     Impulse  FP4 (E2M1)  1.00   0.000000          1.0          0.0
1     Impulse  FP4 (E1M2)  1.00   0.000000          1.0          0.0
2     Impulse  FP8 (E4M3)  0.75   2.498775          0.0          0.0